# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Automatic Save & Restore (tmux-continuum)
set -g @continuum-restore 'on'
set -g @continuum-save-interval '60'


# Resurrect Settings
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'agy vim nvim node python python3 btop htop'

# Manual resurrect bindings
bind -n PageUp copy-mode -u
bind-key S run-shell '~/.tmux/plugins/tmux-resurrect/scripts/save.sh'
bind-key R run-shell '~/.tmux/plugins/tmux-resurrect/scripts/restore.sh'

# Load plugin scripts
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'

